apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          name: whalesay
        spec:
          containers:
            - name: whlaesay
              image: mizzy/whalesay:v0.0.2
          restartPolicy: Never
