apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  # UTCで指定
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        metadata:
          name: whalesay
        spec:
          containers:
            - name: whlaesay
              image: mizzy/whalesay:v0.0.1
          restartPolicy: Never
      backoffLimit: 0
