apiVersion: batch/v1
kind: Job
metadata:
  name: job-
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay:latest
      restartPolicy: Never
  backoffLimit: 4
