apiVersion: batch/v1
kind: Job
metadata:
  name: job-
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: ks-guestbook-demo
        image: mizzy/ks-guestbook-demo:0.1
        command: ["echo"]
        args: ["0.1"]
      restartPolicy: Never
  backoffLimit: 4
